#!/usr/bin/env node

const yargs = require('yargs');
const path = require('path');
const config = require('./lib/app/config');
const I18n = require('./lib/app/i18n');

const i18n = new I18n({
  locales: ['en'],
  default: 'en',
  directory: path.resolve(__dirname, 'locales'),
});
global.i18n = i18n;

config.loadEnv(process.argv);

yargs.commandDir('bin/cmds')
  .option('t', {
    alias: 'timeout',
    describe: i18n.t('global.options.timeout'),
    number: true,
    global: true,
  })
  .demandCommand(1)
  .help()
  .parse();

module.exports = yargs;
