#!/usr/bin/env node

const yargs = require('yargs');
const path = require('path');
const config = require('./lib/app/config');
const I18n = require('./lib/app/i18n');
const { name, version } = require('./package.json');

const i18n = new I18n({
  locales: ['en'],
  default: 'en',
  directory: path.resolve(__dirname, 'locales'),
});
global.i18n = i18n;

config.loadEnv(process.argv);

yargs.commandDir('bin/cmds')
  .strictCommands()
  .option('timeout', {
    describe: i18n.t('global.options.timeout'),
    number: true,
    global: true,
  })
  .option('v', {
    alias: 'verbose',
    describe: i18n.t('global.options.verbose'),
    type: 'boolean',
    global: true,
  })
  .version('version', i18n.t('global.options.version'), `${name} version ${version}`)
  .demandCommand(1, 'You need at least one command before moving on')
  .help()
  .wrap(yargs.terminalWidth())
  .completion('completion', (current, argv, done) => done(yargs.getCommandInstance().getCommands()))
  .parse();

module.exports = yargs;
