const chalk = require('chalk');

exports.available = [
  'id',
  'status',
  'runningTime',
  'createdAt',
  'updatedAt',
  'startedAt',
  'params.sushiId',
  'credentials.endpointId',
  'credentials.endpoint.id',
  'credentials.endpoint.vendor',
  'credentials.institutionId',
  'credentials.institution.id',
  'credentials.institution.name',
  'harvestId',
  'params.username',
  'reportType',
  'params.index',
  'beginDate',
  'endDate',
  'index',
  'forceDownload',
  'timeout',
  'errorCode',
  'result.inserted',
  'result.updated',
  'result.failed',
  'result.errors',
  'result.coveredPeriods',
];

exports.format = {
  runningTime: { type: 'duration' },
  createdAt: { type: 'date' },
  updatedAt: { type: 'date' },
  startedAt: { type: 'date' },
  status: {
    type: 'colorize',
    default: 'white',
    colors: {
      running: chalk.blue,
      cancelled: chalk.yellow,
      interrupted: chalk.red,
      error: chalk.red,
      finished: chalk.green,
    },
  },
};
